---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: e2e-elasticsearch-liveness-
  namespace: e2e
spec:
  activeDeadlineSeconds: 5400
  template:
    metadata:
      name: e2e-elasticsearch-liveness
      namespace: e2e
      labels:
        liveness: e2e-elasticsearch-liveness

        # label used for mass-liveness check upon infra-chaos
        infra-aid: liveness

    spec:
      serviceAccountName: e2e
      restartPolicy: Never
 
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: IfNotPresent
        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            value: default

          - name: LIVENESS_TIMEOUT_SECONDS
            value: "10"

          # number of retries when livenss-fails 
          - name: LIVENESS_RETRY_COUNT
            value: "15"

            # Namespace in which elasticsearch is running
          - name: NAMESPACE
            value: app-esearch-ns 

          - name: LIVENESS_LABEL
            value: 'liveness=elasticsearch-liveness'  

          - name: APPLICATION_LABEL
            value: 'app=elasticsearch'
            
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./apps/elasticsearch/liveness/test.yml -i /etc/ansible/hosts -v; exit 0"]
