---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars.yml

  tasks:
    - block:
        - block:

            - name: Record test instance/run ID
              set_fact:
                run_id: "{{ lookup('env','RUN_ID') }}"

            - name: Construct testname appended with runID
              set_fact:
                test_name: "{{ test_name }}-{{ run_id }}"

          when: lookup('env','RUN_ID')
        
        ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /utils/fcm/update_e2e_result_resource.yml
          vars:
            status: 'SOT'

        - name: Replacing the placeholder for namespace
          replace:
            path: "{{ elasticsearch_liveness }}"
            regexp: "app-namespace"
            replace: "{{ namespace }}"   

        - name: Replacing the placeholder for liveness-retry-count
          replace:
            path: "{{ elasticsearch_liveness }}"
            regexp: "liveness-retry-count"
            replace: "{{ liveness_retry }}"   

        - name: Replacing the placeholder for liveness-timeout
          replace:
            path: "{{ elasticsearch_liveness }}"
            regexp: "liveness-timeout-seconds"
            replace: "{{ liveness_timeout }}"  

        - name : Getting the app service name
          shell: kubectl get svc -n {{ namespace }} -l {{ app_label }} -o jsonpath={.items[0].metadata.name}
          register: name_of_service 

        - name: Getting the port 
          shell: kubectl get endpoints -n {{ namespace }} -l {{ app_label }} -o jsonpath={.items[0].subsets[0].ports[0].port}
          register: port_no

        - name: Replace the placeholder for service name 
          replace:
            path: "{{ elasticsearch_liveness }}"
            regexp: "service_name"
            replace: "{{ name_of_service.stdout }}"

        - name: Replace the placeholder for port number
          replace:
            path: "{{ elasticsearch_liveness }}"
            regexp: "port"
            replace: "{{ port_no.stdout }}"

        - name: Creating elasticsearch-liveness job
          shell: kubectl create -f {{ elasticsearch_liveness }} -n {{ namespace }} 

        - name: Verifying whether liveness pod is started successfully  
          shell: kubectl get pod -n {{ namespace }} -l {{ liveness_label }} -o jsonpath={.items[0].status.phase} 
          register: pod_status
          until: "'Running' in pod_status.stdout"
          delay: 60 
          retries: 20

        - set_fact:
            flag: "Pass"

      rescue:
        - set_fact:
            flag: "Fail"

      always:

        ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /utils/fcm/update_e2e_result_resource.yml
          vars:
            status: 'EOT'
        

