---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: e2e-pgset-
  namespace: e2e
spec:
  template:
    metadata:
      name: e2e
      labels:
        app: postgres-deployment-e2e

    spec:
      serviceAccountName: e2e
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: IfNotPresent

        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

          - name: PROVIDER_STORAGE_CLASS
            # Supported values: openebs-standard,openebs-standalone,local-storage
            value: openebs-standard

          - name: APP_PVC
            value: pgdata-claim

            # Application label
          - name: APP_LABEL
            value: 'app=pgset'

            # Affinity Label for Application
          - name: AFFINITY_LABEL
            value: openebs.io/sts-target-affinity

            # Application namespace
          - name: APP_NAMESPACE
            value: app-pgres-ns

          - name: DEPLOY_TYPE
            value: statefulset
          
            # Use 'deprovision' for app-clean up
          - name: ACTION
            value: provision

            # define a variable CAPACITY to accept the size given by user
          - name: CAPACITY
            value: 5Gi 

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./apps/crunchy-postgres/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"]
