---
apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-openebs-runner
  namespace: e2e 
spec:
  template:
    metadata:
      name: e2e
      labels: 
        provider: openebs-runner
    spec:
      serviceAccountName: e2e
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: IfNotPresent
        env: 
          - name: mountPath
            value: /mnt/openebs
          - name: ANSIBLE_STDOUT_CALLBACK
            value: default
          - name: OPENEBS_VERSION
            value: master
          - name: OPENEBS_MAYA_APISERVER_IMAGE
            value: 
          - name: OPENEBS_PROVISIONER_IMAGE
            value: 
          - name: OPENEBS_SNAPSHOT_CONTROLLER_IMAGE
            value: 
          - name: OPENEBS_SNAPSHOT_PROVISIONER_IMAGE
            value: 
          - name: OPENEBS_IO_JIVA_IMAGE
            value: 
          - name: OPENEBS_MAYA_EXPORTER_IMAGE
            value: 
          - name: OPENEBS_NODE_DISK_MANAGER_IMAGE
            value: 
          - name: OPENEBS_NODE_DISK_OPERATOR_IMAGE
            value: 
          - name: OPENEBS_IO_CSTOR_TARGET_IMAGE
            value: 
          - name: OPENEBS_IO_CSTOR_POOL_IMAGE
            value: 
          - name: OPENEBS_IO_CSTOR_POOL_MGMT_IMAGE
            value: 
          - name: OPENEBS_IO_CSTOR_VOLUME_MGMT_IMAGE
            value: 
          - name: OPENEBS_LOCALPV_PROVISIONER_IMAGE
            value: 
          - name: OPENEBS_ADMISSION_SERVER_IMAGE
            value: 
          - name: OPENEBS_CLEANUP_JOB_IMAGE
            value: 
          - name: IMAGE_PULL_POLICY
            value:
          - name: HELM_REPO
            value:   
          - name: HELM_BRANCH
            value:            
          - name: SPARSE_FILE_COUNT
            value: "10" 
          - name: DEPLOY_MODE
            value: "operator"  
          - name: Action
            value: provision
          - name: OPERATOR_NS
            value: "openebs"
          - name: COMMIT_ID
            value: ""
          - name: RC_TAG
            value: ""

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./providers/openebs/installers/operator/master/e2e-test/test.yml -i /etc/ansible/hosts -vv; exit 0"]
