---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: e2e-cassandra-loadgen-
  namespace: e2e 
spec:
  template:
    metadata:
      name: e2e
      labels:
        loadgen: cassandra-loadjob

    spec:
      serviceAccountName: e2e
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: IfNotPresent
        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: default

          - name: LOADGEN_NS
            value: app-cass-ns

          - name: LOADGEN_LABEL
            value: 'loadgen=cassandra-loadgen'

          - name: APPLICATION_LABEL
            value: 'app=cassandra'

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./apps/cassandra/workload/test.yml -i /etc/ansible/hosts -v; exit 0"]        
