---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: e2e-cockroachdb-
  namespace: e2e
spec:
  template:
    metadata:
      name: e2e
      labels:
        apps: cockroachdb-deployment-e2e

    spec:
      serviceAccountName: e2e
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: IfNotPresent

        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

          - name: PROVIDER_STORAGE_CLASS
            # Supported values: openebs-standard,openebs-standalone,local-storage
            value: openebs-standalone

          - name: APP_PVC
            value: cockroachdb-claim

            # Application label
          - name: APP_LABEL
            value: 'app=cockroachdb'

            # Application namespace
          - name: APP_NAMESPACE
            value: app-cdb-ns

          - name: DEPLOY_TYPE
            value: statefulset

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./apps/cockroachdb/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"]
