---
apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-storageclass-cleanup-jiva-v0.6
  namespace: e2e 
spec:
  template:
    metadata:
      name: e2e
    spec:
      serviceAccountName: e2e
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: IfNotPresent
        env: 
          - name: mountPath
            value: /mnt/openebs
          - name: ANSIBLE_STDOUT_CALLBACK
            value: actionable
          - name: STORAGE_POOL_NAME
            value: openebs-mntdir
          - name: STORAGECLASS_NAME
            value: openebs-storageclass
          - name: STORAGE_PATH
            value: /var/openebs
          - name: JIVA_REPLICA_COUNT 
            value: "3"
          - name: CAPACITY 
            value: 5Gi
          - name: VOLUME_MONITOR 
            value: "true"
          - name: RUN_ID
            value:
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./storageclass/0.6/ansible/storageclass_cleanup.yaml -i /etc/ansible/hosts -vv; exit 0"]
