---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: e2e-nuodb-
  namespace: e2e
spec:
  template:
    metadata:
      name: e2e
      labels:
        app: nuodb-deployment

    spec:
      serviceAccountName: e2e
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: IfNotPresent

        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

          - name: PROVIDER_STORAGE_CLASS
            # Supported values: openebs-standard, local-storage, openebs-standalone
            value: openebs-cstor-sparse

          - name: APP_PVC
            value: demo-vol-claim

          - name: APP_NAMESPACE
            value: nuodbns

            # Application label
          - name: APP_LABEL
            value: 'app=nuodb'

            # Use 'deprovision' for app-clean up
          - name: ACTION
            value: provision

            # Set THP to disable in case platform is AWS or OpenShift
          - name: THP
            value: enable

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./apps/nuodb/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"]
     
