---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - test_vars.yml

  tasks:
    - block:

        ## Generating the testname for deployment
        - include_tasks: /utils/fcm/create_testname.yml

         ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: "/utils/fcm/update_e2e_result_resource.yml"
          vars:
            status: 'SOT'
       
        - include_tasks: /utils/k8s/create_ns.yml

        - block:

            - name: Replace the sc placeholder with ENV sc
              replace:
                path: "{{ item }}"
                regexp: 'testsc'
                replace: '{{ storage_class }}'
              with_items:
                - nuodb.yaml 
                - nuodb-sm.yaml

            - name: Replace Nuodb version
              replace:
                path: "{{ item }}"
                regexp: 'nuodb/nuodb-ce:latest'
                replace: 'nuodb/nuodb-ee:latest'
              with_items:
                - nuodb.yaml 
                - nuodb-sm.yaml
                - nuodb-te.yml
              when: lookup('env','NUODB_VERSION') == 'ee'

            ## Deploying the nuodb service, domain, sm and te 

            - name: Label nodes
              shell: |
                 kubectl label nodes glusterfs=storage-host --all
                 kubectl label nodes node-role.kubernetes.io/compute=true --all
                 kubectl label nodes nuodb.com/zone=a --all
                 kubectl label nodes region=us-east-1 --all
              args:
                executable: /bin/bash
              ignore_errors: true

            - name: Disable THP for platforms like AWS,OpenShift
              shell: kubectl create -f disable-thp.yaml -n {{ app_ns }}
              args:
                executable: /bin/bash
              when: lookup('env','THP') == 'disable' 

            - name: Create secrets for database
              shell: kubectl create -f database-secret.yaml -n {{ app_ns }}
              args:
                executable: /bin/bash

            - name: Deploying NUODB service, domain, storage manager and transaction engines
              shell: kubectl create -f {{ item }} -n {{ app_ns }}
              args:
                executable: /bin/bash
              with_items: "{{ nuodb_spec }}"

            - name: Verify if Nuodb admin, sm and te pods are running
              shell: kubectl get pod -l app={{ item }} -n {{ app_ns }}
              args:
                executable: /bin/bash
              register: result
              with_items: "{{ nuodb_labels }}"
              until: "'Running' in result.stdout"
              delay: 10
              retries: 60

            - set_fact:
                flag: "Pass"  

          when: "'deprovision' not in action"  

        - block:

            - name: Deprovision NUODB service, domain, storage manager and transaction engines
              shell: kubectl delete -f {{ item }} -n {{ app_ns }}
              args:
                executable: /bin/bash
              with_items: "{{ nuodb_spec }}"

            - name: Verify if Nuodb admin, sm and te pods are deleted
              shell: kubectl get pod -l app={{ item }} -n {{ app_ns }}
              args:
                executable: /bin/bash
              register: result
              with_items: "{{ nuodb_labels }}"
              until: "'Running' not in result.stdout"
              delay: 5
              retries: 45

            - set_fact:
                flag: "Pass"  

          when: "'deprovision' is in action"        

      rescue:
        - set_fact:
            flag: "Fail"     

      always:
            ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /utils/fcm/update_e2e_result_resource.yml
          vars:
            status: 'EOT'
              
